'use client'

import './globals.css'
import { Inter } from 'next/font/google'
import { AuthContextProvider } from '@/firebase/AuthContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Interactive NBA History',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    
    <html lang="en">
    <head/>
    <body className={inter.className}>
      <AuthContextProvider>
        {children}
      </AuthContextProvider>
    </body>
  </html>

   
  )
}
